### ISSUE TITLE
beginner question: how to make a transfer operation ?

### ISSUE THREAD

**Issue by wade-liwei** [goat-systems/go-tezos#114]
Could  you give me an example about how to make a transfer  operation ?

**Comment by wade-liwei** [comment]
how to get the branch value  when I want to make a transfer ?

**Comment by 742609298** [comment]
I want an example too,thanks!

**Comment by wade-liwei** [comment]
Now I have the example, I will send it to you when I am free.

**Comment by 742609298** [comment]
@wade-liwei  my mail is hexujunking@163.com，thanks！

**Comment by lmahanand** [comment]
> Now I have the example, I will send it to you when I am free.

are you going to add the example here or share somewhere?

**Comment by DefinitelyNotAGoat** [comment]
Hey Everyone. Sorry for the late response. You can see an example of writing batch transfers in tzpay: https://github.com/goat-systems/tzpay/blob/master/cli/internal/baker/baker.go#L206
