### ISSUE TITLE
[Feture Request] data serialization, contract origination, contract invoke

### ISSUE THREAD

**Issue by qiluge** [goat-systems/go-tezos#138]
Supporting contract origination and invoke is very necessary. And I think there are some utils method at this repo but they are not exported. Such as base58 encode and decode, pack bigNum to string. For convenience, these method should be exported. And in conseilJS, there are many methods to support serialize various data to byte array, and these methods are very useful and helpful. So I wish go-tezos could provide the same feature as conseilJS.

Thanks!

**Comment by DefinitelyNotAGoat** [comment]
Bear with me, contract interaction is on the roadmap for Q2-Q3. I'm going to have to unfortunately disagree on exporting the crypto functions. It's not idiomatic go to expose functions that aren't strictly related to the library. I would consider moving the crypto library into it's own repository with it's own version.
