### ISSUE TITLE
Cannot unmarshal constants

### ISSUE THREAD

**Issue by parmen789** [goat-systems/go-tezos#144]
Hello, I am getting this error when I try to use the example from readme. I am running mainnet node in rolling mode:
could not connect to network: could not initialize library with network constants: could not unmarshal network constants: json: cannot unmarshal string into Go struct field Constants.block_reward of type []*gotezos.Int

I also had problems with go get:

go get github.com/goat-systems/go-tezos/v2
go get: github.com/goat-systems/go-tezos/v2@v2.7.0-alpha requires
	github.com/DefinitelyNotAGoat/go-tezos@v1.0.9: reading github.com/DefinitelyNotAGoat/go-tezos/go.mod at revision v1.0.9: unknown revision v1.0.9

So I downloaded the package in zip and put the contents into v2 directory (Is it possible that I don't have correct version where this problem is fixed?)

**Comment by DefinitelyNotAGoat** [comment]
Yeah, v1.0.9 does not support Carthagenet. There was a breaking change to the JSON schema of constants. 

For Carthagenet please add to go.mod:
```
github.com/goat-systems/go-tezos/v2 v2.8.0-alpha
```
