### ISSUE TITLE
Failed attempt to create a transaction using the example

### ISSUE THREAD

**Issue by Weltburger** [goat-systems/go-tezos#190]
I'm using an example from [example/transaction](https://github.com/goat-systems/go-tezos/blob/master/example/transaction/transaction.go), and I got an error while using the method [InjectionOperation](https://github.com/goat-systems/go-tezos/blob/800cc714fad7313e92a5068407c23e0e397f5323/example/transaction/transaction.go#L66)
Inside this method, we use [Marshal](https://github.com/goat-systems/go-tezos/blob/800cc714fad7313e92a5068407c23e0e397f5323/rpc/independent.go#L68): `v, err := json.Marshal(input.Operation)`, and then we transmit the received data `v` into 
[Client.post](https://github.com/goat-systems/go-tezos/blob/800cc714fad7313e92a5068407c23e0e397f5323/rpc/independent.go#L72) `resp, err := c.post("/injection/operation", v, input.contructRPCOptions()...)`, and now, in this method, the received data is displayed incorrectly immediately after receiving it. 
`func (c *Client) post(path string, body interface{}, opts ...rpcOptions) (*resty.Response, error)`, when entering the method, `body` parameter contains: `<unsupported type: []uint8>`, but before calling the method `c.post`, during debagging, you can see that the transmitted data is correct. As a result, in [this line](https://github.com/goat-systems/go-tezos/blob/800cc714fad7313e92a5068407c23e0e397f5323/rpc/client.go#L106), in `resp` we get `[{"kind":"temporary","id":"failure","msg":"Error while applying operation ooiFyhgHPwwyBepsp19jS2PRzXVFJMnonUdJCbYuGLHAZ5CLtZw:\n branch refused (Error:\n Unrevealed manager key for contract tz1bpzyfVGfFfKiNTHGquRNcbYDLghjcotZa.\n)"}]
`

**Comment by ygcool** [comment]
Hi, have you solved this problem?

**Comment by Weltburger** [comment]
Yes, I just rewrote the function in my package

**Comment by ygcool** [comment]
Can you provide an example that can transfer?

**Comment by Weltburger** [comment]
[Example](https://github.com/Weltburger/golang-cli-tezos-transaction/blob/master/internal/transaction/transaction.go)
