### ISSUE TITLE
All balance values should be returned with the same unit [ MUTEZ ]

### ISSUE THREAD

**Issue by RomarQ** [goat-systems/go-tezos#85]
In my opinion is important that all kind of results share the same unit, there are currently some functions that return values in `mutez` and others that return in `tez`.

For consistency purposes all functions should return the values in **mutez**, leaving the conversion part for the user. ( Helper functions should be implemented so the user can convert between units ).

**This change should be included in the next major release.** 

- [X] Change the functions to return `mutez` instead of `tez`;
- [ ] Implement helper functions to convert between units.

**Comment by RomarQ** [comment]
- [X] Change the functions to return `mutez` instead of `tez`; PR #86

**Comment by utdrmac** [comment]
Just wanted to say that this issue caused me some grief as well. Seems that operations that return "get balance" are returning floats `balance / MUTEZ` while other items, in Block for example, remain as int.
